<?xml version="1.0" encoding="UTF-8"?><testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="10.829791">
<testcase classname="Backoffice Customer" name="List customer and details" time="10.829791">
<failure message="java.lang.IndexOutOfBoundsException: Index: 1, Size: 1&#10;&#9;at java.util.ArrayList.rangeCheck(ArrayList.java:653)&#10;&#9;at java.util.ArrayList.get(ArrayList.java:429)&#10;&#9;at com.friends.testframework.pageobjects.web.CustomerPageObject.getCustomerDetail(CustomerPageObject.java:41)&#10;&#9;at com.friends.testframework.stepdefs.CustomerSteps.iOpenFirstCustomerDetail(CustomerSteps.java:32)&#10;&#9;at ✽.And I open first customer detail(customer.feature:9)&#10;"><![CDATA[Given I am a backoffice user................................................passed
And I login to backoffice with valid credentials............................passed
When I open customer list...................................................passed
And I open first customer detail............................................failed
Then I should see details...................................................skipped

StackTrace:
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.friends.testframework.pageobjects.web.CustomerPageObject.getCustomerDetail(CustomerPageObject.java:41)
	at com.friends.testframework.stepdefs.CustomerSteps.iOpenFirstCustomerDetail(CustomerSteps.java:32)
	at ✽.And I open first customer detail(customer.feature:9)
]]></failure>
</testcase>
</testsuite>
