<?xml version="1.0" encoding="UTF-8"?><testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="69.167777">
<testcase classname="Backoffice Customer" name="Merchant onboarding2" time="69.167777">
<failure message="java.lang.AssertionError&#10;&#9;at org.junit.Assert.fail(Assert.java:86)&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:41)&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:52)&#10;&#9;at com.friends.testframework.stepdefs.CustomerSteps.iShouldSeeSuccessMessage(CustomerSteps.java:127)&#10;&#9;at ✽.Then I should see success message(customer.feature:28)&#10;"><![CDATA[Given I am a backoffice user................................................passed
And I login to backoffice with valid credentials............................passed
And I open new merchant list................................................passed
And I open add merchant.....................................................passed
When I fill form............................................................passed
And I add merchant..........................................................passed
Then I should see success message...........................................failed

StackTrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.friends.testframework.stepdefs.CustomerSteps.iShouldSeeSuccessMessage(CustomerSteps.java:127)
	at ✽.Then I should see success message(customer.feature:28)
]]></failure>
</testcase>
</testsuite>
